[package]
identifier = "{{ identifier }}"
version = "0.1.0"
type = "game"

[runtime]
version = "{{ runtime_version }}"

[build]
input = "./dist" # Your guest code build output, the files you want to package
entrypoint = "game.wasm" # The path to your wasm binary relative to the "input" directory
output = "./bin" # Rune's build output

[bundle]
name = "{{ name }}"

[dependencies]
three = "165.0"
